# Numpy

  

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

## 1 dimensional array

In [4]:
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(a)
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

[1 2 3]
<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]


## 2 dimensional array

In [5]:
import numpy as np

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b)
print(b.shape)                     # Prints "(2, 3)", 2 rows 3 columns
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4
